trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - eks_resources/**

variables:
  imageRepository: 'testreg801.azurecr.io'
  imageTag: '$(Build.SourceVersion)'
  azureSubscription: '0c169943-8f0f-4db5-9dcd-7b56e52a1535'
  appName: 'whiteapp8012'
  containerRegistry: 'docker pull testreg801.azurecr.io'
  imageName: 'newapp'

stages:
- stage: Build
  jobs:
  - job: BuildAndPush
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'testconnecton'
        repository: 'newapp'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'
        tags: '$(imageTag)'
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: $(azureSubscription)
        appName: $(appName)
        imageName: $(containerRegistry)/$(imageName):$(Build.BuildId)