# ci-pipeline.yml
trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - eks_resources/**

variables:
  imageRepository: 'testreg801.azurecr.io'
  imageTag: '$(Build.SourceVersion)'

stages:
- stage: Build
  jobs:
  - job: BuildAndPush
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'testconnecton'
        repository: 'newapp'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'
        tags: '$(imageTag)'

- stage: UpdateManifests
  dependsOn: Build
  jobs:
  - job: UpdateAndCommit
    steps:
    - checkout: self
      persistCredentials: true
      fetchDepth: 0 
    - script: |
        # For standard Kubernetes manifests
        sed -i "s|\(image: \).*|\1$(imageRepository):$(imageTag)|g" eks_resources/deployment.yaml
        git config --global user.email "dania.alrefai@bespinglobal.ae"
        git config --global user.name "Dania"
        git checkout -b $(Build.SourceBranch) 
        git pull origin $(Build.SourceBranch) --rebase
        git add .
        # Commit the image update
        git commit -m "CI: Update image to $(imageTag)"
        
        # Fetch latest changes and rebase
        git fetch origin
        git rebase origin/$(Build.SourceBranch)
        
        # Push changes
        git push origin HEAD:$(Build.SourceBranch)
      displayName: 'Update manifests and commit'
    
    # - task: TriggerPipeline@1
    #   inputs:
    #     serviceConnection: 'azure-devops'
    #     project: '$(System.TeamProject)'
    #     pipeline: 'cd-pipeline'
    #     branch: '$(Build.SourceBranch)'