stages:
- stage: BuildAndPush
  jobs:
  - job: BuildAndPushJob
    steps:
    - script: |
        ./build-and-push-to-ecr.sh ${ECR_URI}
      displayName: 'Build and Push to ECR'
      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)