trigger:  
- task: Bash@3
  inputs:
    filePath: './build-and-push-to-ecr.sh'
    arguments: '${ECR_URI}'
  branches:    
    include:      
      - master
pr: none
stages:
- template: templates/build.yml