trigger:
- master

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildAndPush
  displayName: 'Build and Push to ECR'
  steps:
  - script: |
      echo "Building Docker image..."
      docker build -t my-docker-image:$(Build.BuildId) .
    displayName: 'Build Docker Image'
    
  - script: |
      echo "Logging in to AWS ECR..."
      aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <ECR-URI>
    displayName: 'Login to ECR'
    env:
      AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
      AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
      
  - script: |
      echo "Tagging Docker image..."
      docker tag my-docker-image:$(Build.BuildId) <ECR-URI>/my-docker-image:$(Build.BuildId)
    displayName: 'Tag Docker Image'
    
  - script: |
      echo "Pushing Docker image to ECR..."
      docker push <ECR-URI>/my-docker-image:$(Build.BuildId)
    displayName: 'Push Docker Image to ECR'
