# cd-pipeline.yml
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - eks_resources/**

stages:
- stage: Validate
  jobs:
  - job: ValidateManifests
    steps:
    - script: |
        echo "Installing kubeval with guaranteed download..."
        
        # First try the direct download URL
        KUBEVAL_URL="https://github.com/instrumenta/kubeval/releases/download/v0.16.1/kubeval-linux-amd64.tar.gz"
        
        # Download with strict error handling
        if ! sudo curl -sSL -o kubeval.tar.gz -L "$KUBEVAL_URL"; then
          echo "##vso[task.logissue type=error]Failed to download kubeval"
          exit 1
        fi
        
        # Extract and install
        sudo tar -xzf kubeval.tar.gz -C /usr/local/bin kubeval
        sudo rm kubeval.tar.gz
        
        # Verify the binary
        if ! file /usr/local/bin/kubeval | grep -q "ELF"; then
          echo "##vso[task.logissue type=error]Invalid binary downloaded"
          exit 1
        fi
        
        sudo chmod +x /usr/local/bin/kubeval
        
        # Final verification
        if ! kubeval --version; then
          echo "##vso[task.logissue type=error]kubeval failed after installation"
          exit 1
        fi
        
        echo "Validation..."
        kubeval --strict eks_resources/*.yaml
      displayName: 'Guaranteed kubeval installation'
- stage: Deploy
  dependsOn: Validate
  jobs:
  - deployment: DeployToAKS
    environment: 'dev'
    timeoutInMinutes: 1
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: KubernetesManifest@0
            inputs:
              action: 'deploy'
              kubernetesServiceConnection: 'aksconn'
              namespace: 'default'
              manifests: 'eks_resources/*.yaml'
