name: Build and Push to ACR

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  ACR_NAME: your-acr-name  # Replace with your ACR name
  IMAGE_NAME: your-app     # Replace with your image name

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v4


    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: false
        tags: |
          ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest
          ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
